config/routes.rb
VlawFinance::Application.routes.draw do
  get "charts/debits"

  get "charts/incomes"

  root to: "admin/dashboard#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/admin/debitos/:id/next_status' => "admin/debitos#next_status", via: :get
  match '/admin/debitos/:id/previous_status' => "admin/debitos#previous_status", via: :get

  match '/admin/receita/:id/next_status' => "admin/receita#next_status", via: :get
  match '/admin/receita/:id/previous_status' => "admin/receita#previous_status", via: :get

end

app/views/admin/debitos/_form.html.erb
<%= active_admin_form_for [:admin, @debito], url: (@debito.new_record? ? admin_debitos_path : admin_debito_path(@debito)), method: (@debito.new_record? ? "post" : "put"), :html => { :multipart => true } do |f| %>
	
	<% f.inputs "Débito" do %>
  		<% f.input :person %>
    	<% f.input :client, collection: Person.customers, as: :select %>
  		<% f.input :cost_center %>
      <% f.input :debit_type, as: :radio, collection: Debit.tipo_collection %>
      <% f.input :amount, as: :string, disabled: true %>
  		<% f.input :due_date, as: :datepicker, style: "width: 180px;", html: {class: "vencimento"} %>
  		<% f.input :status, as: :radio, collection: Debit.status_collection %>
  		<% f.input :description %>
  		<%= f.has_many :upload_files do |s| %>
  		  <% s.input :name %>
  		  <% s.input :file_ref, :as => :file %>
      <% end %>
  	<% end %>

  	<%= f.actions %>
    <div class="rails-env" data-env="<%= Rails.env %>" style="display: none;"></div>
<% end %>